name: Build Native Image (CentOS 7 in Docker)

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Native Image in CentOS 7
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Prepare build context
        run: |
          mkdir build-context
          cp -r src jar build-context/
          cp -r src/main/java/com/redxun/util/CompatibilityProcessRepairTool.java build-context/

      - name: Build Native Image in CentOS 7 Docker
        run: |
          docker run --rm -v ${{ github.workspace }}/build-context:/app -w /app centos:7 bash -c "
            yum install -y gcc glibc-devel zlib-devel wget unzip &&
            curl -L -O https://download.oracle.com/graalvm/21/latest/graalvm-community-jdk-21_linux-x64_bin.tar.gz &&
            tar -xzf graalvm-community-jdk-21_linux-x64_bin.tar.gz &&
            export GRAALVM_HOME=\$(pwd)/graalvm-community-* &&
            export PATH=\$GRAALVM_HOME/bin:\$PATH &&
            \$GRAALVM_HOME/bin/gu install native-image &&
            mkdir -p classes &&
            javac -d classes -cp \"jar/*\" src/main/java/com/redxun/util/CompatibilityProcessRepairTool.java &&
            native-image -cp classes:jar/* com.redxun.util.CompatibilityProcessRepairTool compatibility-tool
          "

      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: compatibility-tool-centos7
          path: build-context/compatibility-tool
