name: Build & Verify Native Image

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Native Image with JDK 21 (GraalVM)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Prepare build context
        run: |
          mkdir -p build-context/src/main/java/com/redxun/util
          mkdir -p build-context/jar
          mkdir -p build-context/output
          cp src/main/java/com/redxun/util/CompatibilityProcessRepairTool.java build-context/src/main/java/com/redxun/util/
          cp -r jar/* build-context/jar/

      - name: Compile and build native image using GraalVM JDK 21
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/build-context:/app \
            -w /app \
            -u root \
            ghcr.io/graalvm/native-image-community:21 \
            bash -c "
              mkdir -p /app/output && \
              chmod 777 /app/output && \
              javac -d /app/classes -cp '/app/jar/*' /app/src/main/java/com/redxun/util/CompatibilityProcessRepairTool.java && \
              native-image \
                -cp /app/classes:/app/jar/* \
                -o /app/output/compatibility-tool
                com.redxun.util.CompatibilityProcessRepairTool
          "

      - name: Verify on CentOS 7
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/build-context:/app \
            -w /app/output \
            centos:7 \
            bash -c "./compatibility-tool --version && echo '✅ Runs on CentOS 7 successfully'"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: compatibility-tool-centos7
          path: build-context/output/compatibility-tool
