name: Build & Verify Native Image

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Native Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Prepare build context
        run: |
          mkdir -p build-context/classes
          cp -r src jar build-context/
          cp -r src/main/java/com/redxun/util/CompatibilityProcessRepairTool.java build-context/

      - name: Compile classes
        run: |
          javac -d build-context/classes -cp "jar/*" \
            src/main/java/com/redxun/util/CompatibilityProcessRepairTool.java

      - name: Build native image via GraalVM container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/build-context:/app:Z \
            -w /app \
            ghcr.io/graalvm/native-image-community:21 \
            native-image \
              -cp classes:jar/* \
              com.redxun.util.CompatibilityProcessRepairTool \
              compatibility-tool

      - name: Verify on CentOS 7
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/build-context:/app:Z \
            -w /app \
            centos:7 \
            bash -c "./compatibility-tool --version && echo '✅ runs on CentOS 7!'"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: compatibility-tool-centos7
          path: build-context/compatibility-tool
