name: Build Native Image

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Native Image on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]  # 你也可以加入 macos-latest, windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: '21.0.2'
          java-version: '21'
          distribution: 'graalvm-community'

      - name: Compile Java Class
        run: |
          mkdir -p classes
          javac -d classes -cp "jar/*" src/main/java/com/redxun/util/CompatibilityProcessRepairTool.java

      - name: Build Native Image
        run: |
          native-image \
            -cp classes:jar/* \
            com.redxun.util.CompatibilityProcessRepairTool \
            compatibility-tool

      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: compatibility-tool-${{ matrix.os }}
          path: compatibility-tool
